# Generated by Django 6.0.4 on 2026-05-07 21:01

import voice_clone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audio fayl', 'verbose_name_plural': 'Audio fayllar'},
        ),
        migrations.AddField(
            model_name='audio',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Xatolik xabari'),
        ),
        migrations.AddField(
            model_name='audio',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('processing', 'Ishlov berilmoqda'), ('completed', 'Muvaffaqiyatli yakunlandi'), ('failed', 'Xatolik yuz berdi')], default='pending', max_length=20, verbose_name='Jarayon holati'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to=voice_clone.models.get_generated_path, verbose_name="Sun'iy yaratilgan fayl"),
        ),
        migrations.AlterField(
            model_name='audio',
            name='original_file',
            field=models.FileField(upload_to=voice_clone.models.get_upload_path, verbose_name='Asl audio fayl'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='text',
            field=models.TextField(blank=True, help_text='Ovozdan ajratib olingan matn', verbose_name='Nutq matni (STT)'),
        ),
    ]
