# Generated by Django 6.0.4 on 2026-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_clone', '0002_alter_audio_options_audio_error_message_audio_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='mfcc_data',
            field=models.JSONField(blank=True, null=True, verbose_name="MFCC va Spektral ma'lumotlar"),
        ),
    ]
